//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowService.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StateResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StateResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkflowService.Resources.StateResources", typeof(StateResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj pierwszą pozycję silnika.
        /// </summary>
        internal static string DisplayOneMessage {
            get {
                return ResourceManager.GetString("DisplayOneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj drugą pozycję silnika.
        /// </summary>
        internal static string DisplaySecondMessage {
            get {
                return ResourceManager.GetString("DisplaySecondMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;: Nie pasuje do numeru zamówienia: &apos;{1}&apos;.
        /// </summary>
        internal static string EngineCodeDoesntMachOrderCodeMessageFormat {
            get {
                return ResourceManager.GetString("EngineCodeDoesntMachOrderCodeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeskanuj tabliczkę znamionową pompy.
        /// </summary>
        internal static string InitializedInitMessage {
            get {
                return ResourceManager.GetString("InitializedInitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeskanuj {0} kody silnika.
        /// </summary>
        internal static string MultipleEngineInitFormatMessage {
            get {
                return ResourceManager.GetString("MultipleEngineInitFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeskanuj numer zlecenia.
        /// </summary>
        internal static string PendingInitMessage {
            get {
                return ResourceManager.GetString("PendingInitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeskanuj kolejny kod: {0}....
        /// </summary>
        internal static string ScanMoreEngineCodesMessageFormat {
            get {
                return ResourceManager.GetString("ScanMoreEngineCodesMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeskanuj kod silnika.
        /// </summary>
        internal static string SingleEngineInitMessage {
            get {
                return ResourceManager.GetString("SingleEngineInitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;: Nieznany numer zamówienia. Zeskanuj ponownie.
        /// </summary>
        internal static string UnknownOrderNumberMessageFormat {
            get {
                return ResourceManager.GetString("UnknownOrderNumberMessageFormat", resourceCulture);
            }
        }
    }
}
